data:extend({
    -- -----------------------------------------------------------------------
    -- STARTUP (read during the data stage to build prototypes; requires a
    -- game restart to change, since settings.global is not available yet
    -- when prototypes/*.lua run)
    -- -----------------------------------------------------------------------
    {
        type          = "int-setting",
        name          = "td-core-max-health",
        setting_type  = "startup",
        default_value = 2000,
        minimum_value = 100,
        maximum_value = 10000000,
        order         = "a-a",
    },
    {
        type = "int-setting",
        name = "td-initial-essence-cost",
        setting_type = "startup",
        default_value = 10,
        minimum_value = 1,
        maximum_value = 100,
        order = "a-f",
    },
    {
        type = "int-setting",
        name = "td-essence-cost-multiplier",
        setting_type = "startup",
        default_value = 2,
        minimum_value = 1,
        maximum_value = 10,
        order = "a-g",
    },
    {
        type = "int-setting",
        name = "td-essence-technology-count",
        setting_type = "startup",
        default_value = 5,
        minimum_value = 0,
        maximum_value = 50,
        order = "a-h",
    },
    {
        type = "int-setting",
        name = "td-science-pack-starting-tier",
        setting_type = "startup",
        default_value = 3,
        minimum_value = 1,
        maximum_value = 50,
        order = "a-i",
    },
    {
        type          = "double-setting",
        name          = "td-essence-bonus-initial",
        setting_type  = "startup",
        default_value = 0.08,
        minimum_value = 0.01,
        maximum_value = 1.0,
        order         = "a-j",
    },
    {
        type          = "double-setting",
        name          = "td-essence-bonus-growth",
        setting_type  = "startup",
        default_value = 1.25,
        minimum_value = 1.0,
        maximum_value = 3.0,
        order         = "a-k",
    },
    -- -----------------------------------------------------------------------
    -- RUNTIME-GLOBAL (adjustable mid-game, apply immediately)
    -- -----------------------------------------------------------------------
    {
        type          = "int-setting",
        name          = "td-wave-interval-seconds",
        setting_type  = "runtime-global",
        default_value = 600,
        minimum_value = 30,
        maximum_value = 3600,
        order         = "b-a",
    },
    {
        type          = "int-setting",
        name          = "td-base-wave-size",
        setting_type  = "runtime-global",
        default_value = 5,
        minimum_value = 1,
        maximum_value = 100,
        order         = "b-b",
    },
    {
        type          = "int-setting",
        name          = "td-wave-size-growth",
        setting_type  = "runtime-global",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 50,
        order         = "b-c",
    },
    {
        type          = "int-setting",
        name          = "td-boss-interval",
        setting_type  = "runtime-global",
        default_value = 10,
        minimum_value = 5,
        maximum_value = 50,
        order         = "b-d",
    },
    {
        type          = "int-setting",
        name          = "td-boss-base-health",
        setting_type  = "runtime-global",
        default_value = 3000,
        minimum_value = 100,
        maximum_value = 100000,
        order         = "b-d2",
    },
    {
        type          = "int-setting",
        name          = "td-boss-health-growth",
        setting_type  = "runtime-global",
        default_value = 500,
        minimum_value = 0,
        maximum_value = 50000,
        order         = "b-d3",
    },
    {
        type          = "int-setting",
        name          = "td-aura-radius",
        setting_type  = "runtime-global",
        default_value = 20,
        minimum_value = 5,
        maximum_value = 50,
        order         = "b-f",
    },
    {
        type          = "double-setting",
        name          = "td-aura-damage",
        setting_type  = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 20,
        order         = "b-g",
    },
})
